backend:
  name: git-gateway
  branch: main # Branch que vai mexer no repositório

publish_mode: editorial_workflow # Para fazer um esquema de revisão de novas edições
media_folder: "public/uploads" # Onde os arquivos de mídia serão armazenados
public_folder: "/uploads" # Onde a parte de mídia vai poder ser acessada
#display_url: https://exemplos-da-ide.netlify.app/ # URL que será mostrado no UI do Netlify

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

search: false
locale: 'pt'

collections:


  - label: "Posts"
    name: "posts" # Nome usado da rota
    extension: "json"
    description: "Posts da Relab Jr"
    folder: "content/posts" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.titulo}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Visível", name: "bool", widget: "boolean", default: true}
      - {label: "Gênero", name: "genero", widget: "select", options: ["Outros", "Economia", "Social"], default: ["Outros"]}
      - {label: "Autor(a)", name: "autor", widget: "string", pattern: ['^.{1,30}$', "Máximo 30 carateres."]}
      - {label: "Data", name: "data", widget: "date", date_format: "DD.MM.YYYY"}
      - {label: "Título", name: "titulo", widget: "string", pattern: ['^.{1,40}$', "Máximo 40 carateres."]}
      - {label: "Prévia", name: "previa", widget: "text", pattern: ['^.{1,60}$', "Máximo 60 carateres."]}
      - {label: "Conteúdo", name: "conteudo", widget: "markdown"}
      - {label: "Imagem de Capa", name: "imagemCapa", widget: "image"}


  - label: "Membros"
    name: "Membros"
    extension: "json"
    description: "Membros da Relab Jr"
    folder: "content/membros" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.nome}}" # Nome que vai ficar no URL da página
    fields:
      - {label: "Nome e sobrenome", name: "nome", widget: "string", pattern: ['^.{1,30}$', "Máximo 30 carateres."]}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Posição", name: "posicao", widget: "select",  options: ["Presidência", "Vice-Presidência", "Projetos", "Administrativo Financeiro", "Comercial", "Gestão de Pessoas", "Marketing", "Trainee"], default: ["Trainee"]}
      - {label: "Linkedin", name: "linkedin", widget: "string", required: false}



  - label: "Navbar e Footer"
    name: "navFooter"
    files:
      - label: "Navbar"
        name: "navbar"
        file: "content/navFooter/navbar.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Linkedin", name: "linkedin", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"}

      - label: "Footer"
        name: "footer"
        file: "content/navFooter/footer.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Linkedin", name: "linkedin", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"}
          - {label: "Copyright", name: "copy", widget: "string"}
          - {label: "Watermark1", name: "watermark1", widget: "image"}
          - {label: "Link1", name: "link1", widget: "string"}
          - {label: "Watermark2", name: "watermark2", widget: "image"}
          - {label: "Link2", name: "link2", widget: "string"}
          - {label: "Watermark3", name: "watermark3", widget: "image"}
          - {label: "Link3", name: "link3", widget: "string"}
          - {label: "Background", name: "background", widget: "image"}


# PÁGINAS--------------------------------------------------------------------------------------------------------


  - label: "Páginas"
    name: "paginas"
    files:
      - label: "Home"
        name: "paginaHome"
        file: "content/paginas/home.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Home"
            name: "inicioHome"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto", name: "texto", widget: "markdown"}


          - label: "Imagem Com Botão Resultados"
            name: "imgBotaoRes"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto", name: "texto", widget: "markdown", pattern: ['^.{1,450}$', "Máximo 450 carateres."]}


          - label: "Imagem Com Botão Membros"
            name: "imgBotaoMem"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto", name: "texto", widget: "markdown", pattern: ['^.{1,450}$', "Máximo 450 carateres."]}


          - label: "Nossos Serviços"
            name: "servicosHome"
            widget: "object"
            fields:
              - {label: "Serviço 1", name: "servico1", widget: "string", pattern: ['^.{1,35}$', "Máximo 35 carateres."]}
              - {label: "Imagem 1", name: "imagem1", widget: "image"}
              - {label: "Serviço 2", name: "servico2", widget: "string", pattern: ['^.{1,35}$', "Máximo 35 carateres."]}
              - {label: "Imagem 2", name: "imagem2", widget: "image"}
              - {label: "Serviço 3", name: "servico3", widget: "string", pattern: ['^.{1,35}$', "Máximo 35 carateres."]}
              - {label: "Imagem 3", name: "imagem3", widget: "image"}
              - {label: "Serviço 4", name: "servico4", widget: "string", pattern: ['^.{1,35}$', "Máximo 35 carateres."]}
              - {label: "Imagem 4", name: "imagem4", widget: "image"}
              - {label: "Serviço 5", name: "servico5", widget: "string", pattern: ['^.{1,35}$', "Máximo 35 carateres."]}
              - {label: "Imagem 5", name: "imagem5", widget: "image"}
              - {label: "Serviço 6", name: "servico6", widget: "string", pattern: ['^.{1,35}$', "Máximo 35 carateres."]}
              - {label: "Imagem 6", name: "imagem6", widget: "image"}


          - label: "Conteúdo do Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Linkedin", name: "linkedin", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}




      - label: "Página Quem Somos"
        name: "paginaQuemSomos"
        file: "content/paginas/quemSomos.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Quem Somos"
            name: "inicioQuemSomos"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Texto 1", name: "texto1", widget: "markdown"}
              - {label: "Texto 2", name: "texto2", widget: "markdown"}


          - label: "Carrossel Quem Somos"
            name: "CarrosselQuemSomos"
            widget: "object"
            fields:
              - label: "Imagens Carrossel"
                name: "imagensCarrossel"
                widget: "list"
                min: 3
                max: 10
                field: {label: "Imagem", name: "imagem", widget: "image"}


          - label: "Valores Relab Jr."
            name: "valores"
            widget: "object"
            fields:
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Título 1", name: "titulo1", widget: "string"}
              - {label: "Texto 1", name: "texto1", widget: "markdown", pattern: ['^.{1,100}$', "Máximo 100 carateres."]}
              - {label: "Título 2", name: "titulo2", widget: "string"}
              - {label: "Texto 2", name: "texto2", widget: "markdown", pattern: ['^.{1,100}$', "Máximo 100 carateres."]}
              - {label: "Título 3", name: "titulo3", widget: "string"}
              - {label: "Texto 3", name: "texto3", widget: "markdown", pattern: ['^.{1,100}$', "Máximo 100 carateres."]}
              - {label: "Título 4", name: "titulo4", widget: "string"}
              - {label: "Texto 4", name: "texto4", widget: "markdown", pattern: ['^.{1,100}$', "Máximo 100 carateres."]}


          - label: "Formulário Quem Somos"
            name: "formularioQuemSomos"
            widget: "object"
            fields:
              - {label: "Título", name: "titulo", widget: "string"}
          # VOU DEIXAR PQ VAI QUE USAMOS DPS, MAS EXISTE UM MODELO SÓ PARA OS MEMBROS
          # - label: "Painel Membros"
          #   name: "painelMembros" 
          #   widget: "object" 
          #   fields:
          #     - label: "Membros" 
          #       name: "membros" 
          #       widget: "list"
          #       min: 6
          #       fields:
          #         - label: "Membro"
          #           name: "membro"
          #           widget: "object"
          #           fields:
          #             - {label: "Nome e sobrenome", name: "nome", widget: "string"}
          #             - {label: "Imagem", name: "imagem", widget: "image"}
          #             - {label: "Posição", name: "posicao", widget: "select",  options: ["Presidência", "Vice-Presidência", "Projetos", "Administrativo Financeiro", "Comercial", "Gestão de Pessoas", "Marketing", "Trainee"], default: ["Trainee"]}
          #             - {label: "Linkedin", name: "linkedin", widget: "string", required: false}



      - label: "Página Serviços"
        name: "paginaServicos"
        file: "content/paginas/servicos.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Serviços"
            name: "inicioServicos"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto 1", name: "texto1", widget: "text", pattern: ['^.{1,50}$', "Máximo 50 carateres."]}
              - {label: "Texto 2", name: "texto2", widget: "markdown", pattern: ['^.{1,600}$', "Máximo 600 carateres."]}


          - label: "Serviços Relab Jr."
            name: "servicos"
            widget: "object"
            fields:
              - {label: "Serviço 1", name: "servico1", widget: "string"}
              - {label: "Texto 1", name: "texto1", widget: "markdown", pattern: ['^.{1,550}$', "Máximo 550 carateres."]}
              - {label: "Imagem 1", name: "imagem1", widget: "image"}
              - {label: "Serviço 2", name: "servico2", widget: "string"}
              - {label: "Texto 2", name: "texto2", widget: "markdown", pattern: ['^.{1,550}$', "Máximo 550 carateres."]}
              - {label: "Imagem 2", name: "imagem2", widget: "image"}
              - {label: "Serviço 3", name: "servico3", widget: "string"}
              - {label: "Texto 3", name: "texto3", widget: "markdown", pattern: ['^.{1,550}$', "Máximo 550 carateres."]}
              - {label: "Imagem 3", name: "imagem3", widget: "image"}
              - {label: "Serviço 4", name: "servico4", widget: "string"}
              - {label: "Texto 4", name: "texto4", widget: "markdown", pattern: ['^.{1,550}$', "Máximo 550 carateres."]}
              - {label: "Imagem 4", name: "imagem4", widget: "image"}
              - {label: "Serviço 5", name: "servico5", widget: "string"}
              - {label: "Texto 5", name: "texto5", widget: "markdown", pattern: ['^.{1,550}$', "Máximo 550 carateres."]}
              - {label: "Imagem 5", name: "imagem5", widget: "image"}
              - {label: "Serviço 6", name: "servico6", widget: "string"}
              - {label: "Texto 6", name: "texto6", widget: "markdown", pattern: ['^.{1,550}$', "Máximo 550 carateres."]}
              - {label: "Imagem 6", name: "imagem6", widget: "image"}

          - label: "Formulário Serviços"
            name: "formularioServicos"
            widget: "object"
            fields:
              - {label: "Título", name: "titulo", widget: "string"}

      - label: "Página Blog"
        name: "paginaBlog"
        file: "content/paginas/blog.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Blog"
            name: "inicioBlog"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}


          # ACHO QUE DA PRA PEGAR OS GÊNEROS DOS PRÓPRIOS POSTS
          # - label: "Menu Blog"
          #   name: "menuBlog" 
          #   widget: "object" 
          #   fields:
          #     - label: "Gêneros" 
          #       name: "generos" 
          #       widget: "list"
          #       min: 4
          #       fields:
          #         - label: "Gênero"
          #           name: "genero"
          #           widget: "object"
          #           fields:
          #             - {label: "Gênero", name: "genero", widget: "string"}


# PÁGINAS--------------------------------------------------------------------------------------------------------